# Generated by Django 5.1.3 on 2024-11-24 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='title',
            new_name='section_title',
        ),
    ]
